const countries = [
  "Uzbekistan",
  "Madagascar",
  "Benin",
  "Togo",
  "Burundi",
  "Rwanda",
  "Lesotho",
  "Swaziland",
  "Kyrgyzstan",
  "Papua New Guinea",
  "Ireland",
  "French Guiana",
  "South Sudan",
  "Yemen",
  "Turkmenistan",
  "Tajikistan",
  "Central African Republic",
  "USA",
  "China",
  "India",
  "Russia",
  "Brazil",
  "Australia",
  "Canada",
  "Japan",
  "Germany",
  "France",
  "Italy",
  "Spain",
  "United Kingdom",
  "Mexico",
  "Argentina",
  "South Africa",
  "Egypt",
  "Turkey",
  "Saudi Arabia",
  "South Korea",
  "Indonesia",
  "Pakistan",
  "Bangladesh",
  "Nigeria",
  "Vietnam",
  "Philippines",
  "Thailand",
  "Iran",
  "Colombia",
  "Ukraine",
  "Poland",
  "Malaysia",
  "Chile",
  "Morocco",
  "Greece",
  "Portugal",
  "Netherlands",
  "Belgium",
  "Sweden",
  "Switzerland",
  "Norway",
  "Austria",
  "Finland",
  "Denmark",
  "New Zealand",
  "Israel",
  "Singapore",
  "Hong Kong",
  "Taiwan",
  "Czech Republic",
  "Hungary",
  "Romania",
  "Slovakia",
  "Bulgaria",
  "Croatia",
  "Serbia",
  "Kazakhstan",
  "Azerbaijan",
  "Armenia",
  "Georgia",
  "Lithuania",
  "Latvia",
  "Estonia",
  "Slovenia",
  "Iceland",
  "Luxembourg",
  "Monaco",
  "San Marino",
  "Liechtenstein",
  "Malta",
  "Andorra",
  "Cyprus",
  "Qatar",
  "Kuwait",
  "Bahrain",
  "United Arab Emirates",
  "Oman",
  "Jordan",
  "Lebanon",
  "Syria",
  "Iraq",
  "Afghanistan",
  "Sri Lanka",
  "Nepal",
  "Bhutan",
  "Maldives",
  "Myanmar",
  "Cambodia",
  "Laos",
  "Mongolia",
  "North Korea",
  "Belarus",
  "Moldova",
  "Bosnia and Herzegovina",
  "Albania",
  "Macedonia",
  "Montenegro",
  "Kosovo",
  "Greenland",
  "Honduras",
  "Nicaragua",
  "Guatemala",
  "Panama",
  "Costa Rica",
  "El Salvador",
  "Cuba",
  "Dominican Republic",
  "Haiti",
  "Jamaica",
  "Trinidad and Tobago",
  "Barbados",
  "Saint Lucia",
  "Saint Vincent and the Grenadines",
  "Grenada",
  "Antigua and Barbuda",
  "Saint Kitts and Nevis",
  "Belize",
  "Guyana",
  "Suriname",
  "Venezuela",
  "Paraguay",
  "Uruguay",
  "Bolivia",
  "Ecuador",
  "Peru",
  "Ghana",
  "Kenya",
  "Uganda",
  "Tanzania",
  "Ethiopia",
  "Somalia",
  "Sudan",
  "Libya",
  "Algeria",
  "Tunisia",
  "Senegal",
  "Ivory Coast",
  "Burkina Faso",
  "Mali",
  "Niger",
  "Chad",
  "Cameroon",
  "Gabon",
  "Equatorial Guinea",
  "Namibia",
  "Botswana",
  "Zimbabwe",
  "Mozambique",
  "Zambia",
  "Malawi",
  "Angola",
  "Democratic Republic of the Congo",
  "Republic of the Congo",
  "Gambia",
  "Guinea",
  "Guinea-Bissau",
  "Sierra Leone",
  "Liberia",
  "Mauritania",
  "Cape Verde",
  "Sao Tome and Principe",
  "Mauritius",
  "Seychelles",
  "Comoros",
  "Djibouti",
  "Eritrea",
  "Western Sahara",
  "Palestine",
  "Vatican City",
];

export default countries;
