export default function getCountryCode(country) {
  const countryCodes = {
    Uzbekistan: "UZB",
    Madagascar: "MDG",
    Benin: "BEN",
    "Papua New Guinea": "PNG",
    Kyrgyzstan: "KGZ",
    Swaziland: "SWZ",
    Burundi: "BDI",
    Togo: "TGO",
    Lesotho: "LSO",
    Ireland: "IRL",
    Rwanda: "RWA",
    Tajikistan: "TJK",
    Yemen: "YEM",
    Turkmenistan: "TKM",
    "Central African Republic": "CAF",
    "South Sudan": "SSD",
    "French Guiana": "GUF",
    USA: "USA",
    China: "CHN",
    India: "IND",
    Russia: "RUS",
    Brazil: "BRA",
    Australia: "AUS",
    Canada: "CAN",
    Japan: "JPN",
    Germany: "DEU",
    France: "FRA",
    Italy: "ITA",
    Spain: "ESP",
    "United Kingdom": "GBR",
    Mexico: "MEX",
    Argentina: "ARG",
    "South Africa": "ZAF",
    Egypt: "EGY",
    Turkey: "TUR",
    "Saudi Arabia": "SAU",
    "South Korea": "KOR",
    Indonesia: "IDN",
    Pakistan: "PAK",
    Bangladesh: "BGD",
    Nigeria: "NGA",
    Vietnam: "VNM",
    Philippines: "PHL",
    Thailand: "THA",
    Iran: "IRN",
    Colombia: "COL",
    Ukraine: "UKR",
    Poland: "POL",
    Malaysia: "MYS",
    Chile: "CHL",
    Morocco: "MAR",
    Greece: "GRC",
    Portugal: "PRT",
    Netherlands: "NLD",
    Belgium: "BEL",
    Sweden: "SWE",
    Switzerland: "CHE",
    Norway: "NOR",
    Austria: "AUT",
    Finland: "FIN",
    Denmark: "DNK",
    "New Zealand": "NZL",
    Israel: "ISR",
    Singapore: "SGP",
    "Hong Kong": "HKG",
    Taiwan: "TWN",
    "Czech Republic": "CZE",
    Hungary: "HUN",
    Romania: "ROU",
    Slovakia: "SVK",
    Bulgaria: "BGR",
    Croatia: "HRV",
    Serbia: "SRB",
    Kazakhstan: "KAZ",
    Azerbaijan: "AZE",
    Armenia: "ARM",
    Georgia: "GEO",
    Lithuania: "LTU",
    Latvia: "LVA",
    Estonia: "EST",
    Slovenia: "SVN",
    Iceland: "ISL",
    Luxembourg: "LUX",
    Monaco: "MCO",
    "San Marino": "SMR",
    Liechtenstein: "LIE",
    Malta: "MLT",
    Andorra: "AND",
    Cyprus: "CYP",
    Qatar: "QAT",
    Kuwait: "KWT",
    Bahrain: "BHR",
    "United Arab Emirates": "ARE",
    Oman: "OMN",
    Jordan: "JOR",
    Lebanon: "LBN",
    Syria: "SYR",
    Iraq: "IRQ",
    Afghanistan: "AFG",
    "Sri Lanka": "LKA",
    Nepal: "NPL",
    Bhutan: "BTN",
    Maldives: "MDV",
    Myanmar: "MMR",
    Cambodia: "KHM",
    Laos: "LAO",
    Mongolia: "MNG",
    "North Korea": "PRK",
    Belarus: "BLR",
    Moldova: "MDA",
    "Bosnia and Herzegovina": "BIH",
    Albania: "ALB",
    Macedonia: "MKD",
    Montenegro: "MNE",
    Kosovo: "KOS",
    Greenland: "GRL",
    Honduras: "HND",
    Nicaragua: "NIC",
    Guatemala: "GTM",
    Panama: "PAN",
    "Costa Rica": "CRI",
    "El Salvador": "SLV",
    Cuba: "CUB",
    "Dominican Republic": "DOM",
    Haiti: "HTI",
    Jamaica: "JAM",
    "Trinidad and Tobago": "TTO",
    Barbados: "BRB",
    "Saint Lucia": "LCA",
    "Saint Vincent and the Grenadines": "VCT",
    Grenada: "GRD",
    "Antigua and Barbuda": "ATG",
    "Saint Kitts and Nevis": "KNA",
    Belize: "BLZ",
    Guyana: "GUY",
    Suriname: "SUR",
    Venezuela: "VEN",
    Paraguay: "PRY",
    Uruguay: "URY",
    Bolivia: "BOL",
    Ecuador: "ECU",
    Peru: "PER",
    Ghana: "GHA",
    Kenya: "KEN",
    Uganda: "UGA",
    Tanzania: "TZA",
    Ethiopia: "ETH",
    Somalia: "SOM",
    Sudan: "SDN",
    Libya: "LBY",
    Algeria: "DZA",
    Tunisia: "TUN",
    Senegal: "SEN",
    "Ivory Coast": "CIV",
    "Burkina Faso": "BFA",
    Mali: "MLI",
    Niger: "NER",
    Chad: "TCD",
    Cameroon: "CMR",
    Gabon: "GAB",
    "Equatorial Guinea": "GNQ",
    Namibia: "NAM",
    Botswana: "BWA",
    Zimbabwe: "ZWE",
    Mozambique: "MOZ",
    Zambia: "ZMB",
    Malawi: "MWI",
    Angola: "AGO",
    "Democratic Republic of the Congo": "COD",
    "Republic of the Congo": "COG",
    Gambia: "GMB",
    Guinea: "GIN",
    "Guinea-Bissau": "GNB",
    "Sierra Leone": "SLE",
    Liberia: "LBR",
    Mauritania: "MRT",
    "Cape Verde": "CPV",
    "Sao Tome and Principe": "STP",
    Mauritius: "MUS",
    Seychelles: "SYC",
    Comoros: "COM",
    Djibouti: "DJI",
    Eritrea: "ERI",
    "Western Sahara": "ESH",
    Palestine: "PSE",
    "Vatican City": "VAT",
  };
  return countryCodes[country];
}
